#!/usr/bin/env python3
"""Derive a CONTENT fingerprint of the validator's C++ sources (ABT #397).

ABT #397: several out-of-source build directories (build/, build-ninja/,
build-capaudit/, ...) all configure against the SAME validator/src, but each
is only as fresh as its own last rebuild. Nothing stopped a consumer from
importing a .so that was built hours before the source it was supposedly
compiled from was last edited -- and it already cost a real investigation
(ABT #552 was chased against a stale build that predated the fix by hours).
A directory-naming convention ("build/ is canonical") cannot catch that: the
canonical directory itself can still be stale relative to the tree.

The fix is a fingerprint over CONTENT, not a timestamp: this script hashes
every check-relevant source file (validator/src/*.cpp,
validator/include/tas_validator/*.hpp) in a fixed, sorted order. The exact
same function runs twice:

  1. At BUILD time (CMakeLists.txt custom command) -- the result is baked
     into the compiled module as `tas::build_fingerprint()` /
     `tas_validator.build_fingerprint()` in Python.
  2. At VERIFICATION time (check_freshness.py, or
     tests/test_validator.cpp's guard test) -- recomputed fresh from
     whatever is on disk RIGHT NOW and compared against #1.

A mismatch means the loaded module was compiled from different source
content than what is on disk today -- i.e. it is stale, full stop, regardless
of which build-* directory it came from or what its mtime says. Because both
sides call this SAME function, there is no second hashing implementation to
drift out of parity (the failure mode that would defeat a "reimplement the
same hash in C++" approach).

Usage:
    gen_build_fingerprint.py --validator-dir DIR --print
    gen_build_fingerprint.py --validator-dir DIR --emit-header OUT.inc
"""
import argparse
import hashlib
import sys
from pathlib import Path


def fingerprinted_files(validator_dir: Path):
    """Every file whose content participates in the fingerprint, sorted so
    the hash is order-independent of filesystem iteration order. Restricted
    to files that actually affect check behavior: the check-family .cpp
    files and the public/shared headers they compile against. Deliberately
    EXCLUDES generated/ (that's an output of the build, not an input) and
    bindings.cpp (pybind11 glue only, not physics)."""
    src_dir = validator_dir / "src"
    include_dir = validator_dir / "include" / "tas_validator"
    if not src_dir.is_dir():
        raise FileNotFoundError(f"no such source dir: {src_dir}")
    if not include_dir.is_dir():
        raise FileNotFoundError(f"no such include dir: {include_dir}")
    files = sorted(src_dir.glob("*.cpp")) + sorted(include_dir.glob("*.hpp"))
    if not files:
        raise RuntimeError(
            f"fingerprinted_files found ZERO files under {src_dir} / {include_dir} "
            "-- almost certainly a wrong --validator-dir, not an empty validator. "
            "Refusing to emit a fingerprint over nothing."
        )
    return files


def compute_fingerprint(validator_dir: Path) -> str:
    """sha256 over relpath + content for every fingerprinted file, in sorted
    order. Deterministic across machines: no mtimes, no absolute paths, no
    filesystem ordering dependence."""
    validator_dir = Path(validator_dir)
    h = hashlib.sha256()
    for f in fingerprinted_files(validator_dir):
        rel = f.relative_to(validator_dir).as_posix()
        content = f.read_bytes()
        h.update(rel.encode("utf-8"))
        h.update(b"\0")
        h.update(str(len(content)).encode("ascii"))
        h.update(b"\0")
        h.update(content)
        h.update(b"\0")
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--validator-dir", required=True,
                     help="path to the validator/ directory (containing src/ and include/)")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--print", action="store_true", dest="do_print",
                       help="print the hex fingerprint to stdout")
    mode.add_argument("--emit-header",
                       help="write a C++ header defining kBuildFingerprint to this path")
    args = ap.parse_args()

    fingerprint = compute_fingerprint(Path(args.validator_dir))

    if args.do_print:
        print(fingerprint)
    else:
        # A bare string-literal expression, included as the body of a
        # `return #include "...inc";` statement (same idiom as
        # check_codes.inc's braced initializer-list) -- not a standalone
        # declaration, so it drops straight into build_info.cpp's return.
        text = (
            "// GENERATED by tools/gen_build_fingerprint.py -- do not hand-edit.\n"
            "// Content fingerprint of validator/src/*.cpp + "
            "validator/include/tas_validator/*.hpp as of this build (ABT #397).\n"
            f'"{fingerprint}"\n'
        )
        Path(args.emit_header).write_text(text)


if __name__ == "__main__":
    sys.exit(main())
